### ISSUE TITLE
Carballo v1.5 with SJCE interface for Java engines

### ISSUE THREAD

**Issue by yellow-panther** [albertoruibal/carballo#1]
Roman Koldaev https://sourceforge.net/p/sjce/ said: For Carballo engine return to support version 1.4 - because v1.5 very often output "bestmove none" in the middle of the game 

He created the SJCE interface https://sourceforge.net/projects/sjce/ for WB/UCI compatible chess engines written in Java

harp07@mail.ru is his email-address (for further questions)

**Comment by albertoruibal** [comment]
I found a possible concurrence problem and it will be fixed in the upcoming Carballo 1.6.
Thank you!
