### ISSUE TITLE
UCI_LimitStrength is missing

### ISSUE THREAD

**Issue by insanetesterftw** [albertoruibal/carballo#2]
According to the UCI protocol, from here: http://wbec-ridderkerk.nl/html/UCIProtocol.html, **UCI_Elo** should be implemented together with **UCI_LimitStrenght**

Quote from the UCI protocol:

> = UCI_LimitStrength, type check, should be false by default,
>The engine is able to limit its strength to a specific Elo number,
> This should always be implemented together with "UCI_Elo".
> = UCI_Elo, type spin
>The engine can limit its strength in Elo within this interval.
>If UCI_LimitStrength is set to false, this value should be ignored.
>If UCI_LimitStrength is set to true, the engine should play with this specific strength.
>This should always be implemented together with "UCI_LimitStrength".

**Comment by albertoruibal** [comment]
I didn't knew about this option. In Carballo 1.8 I will change the current non standard "Elo" Uci option by this pair of Uci options. Thank you!

**Comment by insanetesterftw** [comment]
That's great, thank you.
