### ISSUE TITLE
Carballo exits ponder mode on its own

### ISSUE THREAD

**Issue by ilaripih** [albertoruibal/carballo#5]
I was investigating a Cute Chess issue regarding Carballo here: https://github.com/cutechess/cutechess/issues/180

As you can see in the engine communication log section I just posted, this happens:

1. Carballo receives `go ponder wtime 51942 btime 62649`
2. After thinking for a while Carballo sends `bestmove b2c3 ponder e5e4` to Cute Chess even though Cute Chess never sent "stop" or "ponderhit" to Carballo.

I think this happens because Carballo hits maximum search depth (and/or mate score), but according to the UCI protocol specs: "Do not exit the search in ponder mode, even if it's mate!"

**Comment by albertoruibal** [comment]
Thank you for your report, I'm writing a fix fo avoid sending bestmove in ponder mode.

**Comment by ilaripih** [comment]
Thanks for the fix. Does Carballo still send "bestmove" when it receives the "stop" command in ponder mode?

**Comment by albertoruibal** [comment]
Ooops, with the current fix it does not send bestmove after stop or ponderhit. I'm pushing a fix with a proper solution and the test case. Thank you!
